### ISSUE TITLE
Remove duplicate macro definitions from sl_wfx_host.c

### ISSUE THREAD

**Issue by tomlogic** [SiliconLabs/wfx-fullMAC-tools#5]
In multiple samples, you're defining two macros in both the header and source file.

```
#define SL_WFX_MAX_STATIONS     8
#define SL_WFX_MAX_SCAN_RESULTS 50
```

Recommend removing the definitions from the .c file so a change in the .h doesn't result in a conflict.

**Comment by silabs-JulienT** [comment]
Hi Tom, 

Thanks for the report. We will address the issue in our next update.

Regards,
Julien

**Comment by silabs-JulienT** [comment]
Duplication removed
